# Generated by Django 3.2 on 2021-04-21 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_alter_extendeduser_dateofbirth'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='token',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
    ]
