# Generated by Django 3.2 on 2021-04-21 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_studentdetails_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmarks',
            name='examdate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
